### ISSUE TITLE
[1.10] Keys not using items referenced in items.conf

### ISSUE THREAD

**Issue by jsnbrown1989** [SimonFlash/TeslaCrate#1]
[Current Nucleus Info](https://cdn.discordapp.com/attachments/319162038150627329/326422386067111938/nucleus-info-20170619-200432.txt)

It looks like Key ids are not looking in the item.conf. I have to specify the item via minecraft:item. Only then does it work.

```
weber {
    display-name="Weber Key"
    physical {
        item {
            id="minecraft:tripwire_hook"
        }
    }
}
```

You stated this is a Sponge issue in chat but I did want to list this here to remind you to remove {lever} from the default config as the example. Otherwise you will be questioned about this in the future.

**Comment by SimonFlash** [comment]
Cause by treating the item as a list of items where 'item' itself was the reference name rather than as a singleton. This issue has been fixed and has also been addressed for the other builders as well.

My ignition belief of this being a Sponge issue was incorrect; successful tests were made on SF-1.10.2-2379 and SF-1.10.2-2401. Minecraft itself processes id's such as 'slime' as the equivalent of 'minecraft:slime'. I am unsure what might be interfering with that, but I will update the default config to avoid any future issues. I'll speak to you further on this.

Closed as the original issue has been resolved.
