### ISSUE TITLE
Can't set location

### ISSUE THREAD

**Issue by LemADEC** [SimonFlash/TeslaCrate#11]
As of TeslaCrate-s7.1-t1.1.5-v3.0.0-pr3 + TeslaPowered-s7.1-v1.1.5, location can't be set: it always reports the crate has being not defined.
Also, pressing the 'TAB' key will not autocomplete after `/teslacrate location set #target ` or `/teslacrate info crate `.
I've tried with the default configuration under tesla, teslacrate and &eTesla&6Crate ids without much success.
Adding my own test crate didn't help either.
The crate menu is also empty.

The default skeleton key does show up in the menu, but it's not recognized in `/teslacrate info key skeleton`.

When a parsing error happens, it's reported as info instead of error, which makes it harder to catch in the logs. Also, the error isn't reported on reload with `/sponge -g reload`, is it supported?

**Comment by LemADEC** [comment]
Downgrading to TeslaCrate-s7.1-t1.1.2-v2.2.1 doesn't help either.

**Comment by SimonFlash** [comment]
1. There are way too many problems listed here. One issue, one problem.
2. Version 2 cannot be compared to version 3. They are not the same plugin.

In response to the issues, here are the ones I have pulled out:
 - The info command does not have tab completion because it's structure is different. It is a temporary debugging command until better systems can be established.
 - All logging messages are sent to the server as a Text message. You should look for the initialization messages for the config which are right when the server starts.
 - `sponge -g reload` reloads the Sponge config. You want `sponge plugins reload teslacrate`.

The default config has some errors with it; this is noted in the release description clearly. As I cannot replicate any of the other problems given with a working configuration, I'm going to presume that your config is malformed and these other issues are directly caused by that. If you can provide a working configuration in which I can replicate this, then I'll reopen the issue as need be.

**Comment by LemADEC** [comment]
Yes, we have way too many issues for this plugin, it wouldn't make sense to split it when it's probably a single point of failure.

Version 2 was tested with default configuration and didn't work with core 1.1.5:
[2.zip](https://github.com/SimonFlash/TeslaCrate/files/2364132/2.zip)

Version 3 was patched as per release note (changing id to type), and didn't work with core 1.1.5:
[3.zip](https://github.com/SimonFlash/TeslaCrate/files/2364133/3.zip)

Version 2 seems to work better with core 1.1.2. We only tested creating a single default location.

Version 2 with core 1.1.2 also have the errors reported as info in the server logs:
```
[06:56:15] [Server thread/INFO] [minecraft/DedicatedServer]: teslacrate/ERROR: Unable to load config file crates.conf.
[06:56:15] [Server thread/INFO] [minecraft/DedicatedServer]: teslacrate/ERROR: Unable to initialize configuration: configurate.typesafe.config.ConfigException$Parse: Reader: 30: unbalanced close brace '}' with no open brace (if you intended '}' to be part of a key or string value, try enclosing the key or value in double quotes)
```
