### ISSUE TITLE
Remove Converter

### ISSUE THREAD

**Issue by codeHusky** [SimonFlash/TeslaCrate#6]
Please remove the converter from HuskyCrates to TeslaCrate.

I have no legal grounds to demand this and you aren't obligated to do so, but I request for you to remove it.

Edited from the original cooyright-based request

**Comment by Rasgnarok** [comment]
If you could explain how different it is from https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/griefprevention/migrator/RedProtectMigrator.java or https://github.com/Flibio/EconomyLite/blob/master/src/main/java/io/github/flibio/economylite/commands/MigrateCommand.java#L118, that would be excellent. 

There is little legal basis for _formatting_ to be under a license. We could also discuss at length the difference between treating a config file, supplying it. Tesla Crates only uses the information the user provides. This already shows misinterpretation on your behalf. In truth, the GPLv3 license addresses very little your claim. Once again, I'd like to see precedent, where hereditary libraries is properly defined in this context. Tesla Crates does NOT depend on HuskyCrates to function, and as such cannot constitute a child work of the main JAR. Were we to define Tesla Creates as "[single work derived from both the library code and the application code](https://www.gnu.org/licenses/lgpl-java.html)", where the application is Simon's work and your plugin is the library, we might have grounds to your claim. But we do not, as this is not a core/parent-dependency/child relationship. Please read the link provided fully, as it explains further down how exactly GPLv3 defines this relationship.

Moreover, there is reason here to say that your ticket is _not_ an issue, merely a bias claim that could have been addressed directly to the developer. Placing it here, without heavily supplying your quite serious claim simply calls for more legalese that surely neither you, or the dev, or the users of the plugin care for. 

I would then ask you that lastly, you please address this issue with a fully informed and substantiated claim that covers the precedents already set by the likes of GriefPrevention, Luckperms, PermissionsEX, TotalEconomy, LiteEconomy, EssentialCmds... you get my point. The fact is, **no** plugin has had to abide by your request. Most importantly, no developer has demanded it either - which begs the question, _why_ did you?

Either way, this ticket contains very little, both regarding precedents and licensing, as well as the very aims behind it. I move for @SimonFlash to close this.

**Comment by codeHusky** [comment]
Sure, close it.

But, as the configuration format is an extension of HuskyCrate's code, I'd say that it falls under copyright.

I can't really do anything if Simon decides not to abide, and I haven't C&D'd or anything since I don't have the right to do so in this case, as this is relatively grey. The license technically applies to the configuration format, but there isn't anything directly including or excluding that config format as per the wording of the license.

Again, no need to comply with this, I'm just trying to advise under the advice of the license itself.

**Comment by Rasgnarok** [comment]
The first post on this ticket demands compliance. I am glad we agree it is beyond the mandate of your current license, as there cannot be compliance if there is no legal grounds or precedents. Any action, such as C&D, would not be granted under these two previous points. Because would there be reasonable cause, we would not be disagreeing with the same sources - specifically what GPLv3 has to say about Java inheritance.
Yes, the ticket should be closed.

**Comment by codeHusky** [comment]
The main point of this is just to express my distaste for the decision to include a converter in this plugin. I won't be including a converter in my own plugin for the sake of friendly competition, and I hope Simon will see the appeal of that soon.

**Comment by NickImpact** [comment]
Friendly competition always goes back and forth. If you truly wanted to make things friendly, for both you and Simon, as well as the community, you wouldn’t complain about a converter, and would add one yourself. That way, a user can have the ability to switch back and forth at their pleasure. I’ve seen way too much of these “dick measuring contests” out of you, and if you ask me, that is what is distasteful here. I commend Simon for his decision to add a converter, he just helped the community of users in their aid of converting, if they ever do decide to.

**Comment by codeHusky** [comment]
> If you truly wanted to make things friendly, for both you and Simon, as well as the community, you wouldn’t complain about a converter, and would add one yourself.

That directly goes against my earlier statement as I don't believe that's really all that friendly, but okay. I don't like inter-plugin converters because I just think they're relatively rude to the other developer, and really they're bound to break or cause things to work in unexpected ways.

> I’ve seen way too much of these “dick measuring contests” out of you...

Uh? Alright. I'm not sure exactly what you're referring to, but say what you wish, I suppose. Accusations like that without any substantial evidence or anything aren't appreciated.


Anyway, I'm closing this, since there's no point in continuing this discussion. There's nothing more to be said, rather.

**Comment by NickImpact** [comment]
You wanted server owners to pay you for your plugin services, along with multiple instances of you either attacking TeslaCrates for its existence, or just superiority as it grows stronger. Claim all you want, but the evidence is all over the sponge forums, and github itself.

**Comment by codeHusky** [comment]
> pay you for your plugin services
Which was, as I said before, a late night thing that shouldn't have happened.

> attacking TeslaCrates for its existence, or just superiority as it grows stronger
I've never attacked TeslaCrate or SimonFlash. Pointing out flaws of a project is not an attack, it's a criticism. 

Any evidence you have is going to be incredibly biased, and there's no sense in starting pointless drama where there need not be.

**Comment by Mikirae** [comment]
You're just mad because TeslaCrate has too much swag even on its hoverboard.

**Comment by codeHusky** [comment]
I'm sure this was posted in the SimonFlash discord and now everyone's decided to jump on the hate train. Thanks, very classy.

**Comment by codeHusky** [comment]
I thought it deserved some public input, and everyone's made their stance on this pretty clear. That's why the issue is closed.

**Comment by NickImpact** [comment]
I actually have no bias. I have my own crates plugin that I can publish at any time. I just prefer to defend people in the right rather than the wrong.

**Comment by codeHusky** [comment]
Nick, I don't really care if you have this crates plugin you keep mentioning. Go ahead and publish it. I'm sure it's cool, and I'd like to see what it's like, if I'm honest. 

Again, I don't care how many crates plugins there are, or how many re-implementations of the same idea there are on Ore / the forums. All I care about is people being fair and nice to each other, and really, ever since that one slip-up I had on the forums at like 2am, you've grown to have a bit of an inherit bias against me. 

I'd appreciate it if you just would lay off and treat me like a human being, but that's not something I can control.

**Comment by NickImpact** [comment]
I am treating you like a human being. What I’m enacting is what many of us like to call “Being a dick”, where one individual throws shit into perspective for the other to learn from their mistakes. That is all this is, accept it or don’t. Take care now, I’ve got a nice meal of del taco to eat, so my roast has ended. ✌🏻

**Comment by codeHusky** [comment]
Uh, okay, you can "be a dick" in public if you want.

I don't get why you feel the need to since I haven't done anything all that wrong, but alright.

**Comment by Andre601** [comment]
> I don't get why you feel the need to since I haven't done anything all that wrong, but alright.

\*Looks at the first message in this issue* Really?

**Comment by codeHusky** [comment]
Okay, I don't understand why everyone's getting so needlessly heated. all this is was me being kinda irritated that Simon added a config converters in his plugin when nobody else (eg GWM) has done that. I wouldn't have been so miffed if he had asked permission but he didn't.

And yes, you CAN copyright configuration formats but my projects license doesn't cover that. I wasn't sure if I had legal grounds to begin with and that's why I asked in here. For public input. People have made themselves very clear and repeating that further isn't doing anything but wasting time.

**Comment by codeHusky** [comment]
I apologise for causing all the mess in this issue. As with most of my mistakes, it was late and I let myself make a decision to act in a matter of minutes rather than giving it serious thought. In hindsight this should've been addressed differently, asking publicly what people think about config converters or the copyright related to such, off of GitHub, and gaguing my reaction based on that.

I didn't realize this would cause the absolute mess it has in the replies to this issue. I won't be copyrighting my config format or really doing this again, I can assure you of that.

Apologies to Simon for causing a mess in here, and I've reduced this comment to just a request since the previous statement had no basis.

**Comment by SimonFlash** [comment]
I had left this open because I had originally felt that there was valid discussion to be had, but this quickly turned to disarray overnight. I'd like to clarify that under no circumstances did I attempt to provoke or condone responses of any type, you brought that upon yourself.

Legally, there is no foundation supporting your claim - perhaps if you had said this from the beginning rather than demanding it to be removed things would have turned out differently. After speaking with a lawyer from my college's Legal Services department, you must have a patent for your file format in order to have legal grounds to prevent another's use of it. In the United States, these are primarily given to protect proprietary encoding systems, such as the RAR compression algorithm. Given that you do not have a patent and it is formatted in HOCON (which you do not control), you have no jurisdiction for a copyright claim.

From developer to developer, I would be more willing to accommodate your requests if you were actually concerned about your work being credited instead of this being politically motivated. I am most upset by the fact that you created an issue for it *after* tagging me to discuss it in the Sponge discord. If you had legitimate grievances, they should be addressed through direct messages rather than in public (which is how a proper copyright claim would be made). As you said yourself: `The main point of this is just to express my distaste for the decision to include a converter in this plugin.` 

On the subject of friendly competition, note that a converter has been the most requested feature since May of last year - and I haven't acted on that until now. It was actually @NickImpact who got me thinking about this when I saw their crate plugin (which has like, super cool animations and stuff). I would definitely feel a bit aggravated if he decided to release it, but at the same time I would be motivated to bring my particle effects and animations up to that level so I can beat him in that too. This is what he was referring to by friendly competition, and over time things might change - zml and Hassan now back LuckPerms and Nucleus respectively. From the looks it, of my update seems to have inspired a total rewrite on your behalf.

The primary aspect here with friendly competition is the idea that people are able to choose which plugin they want to use freely, with the largest (and ideally only) restriction being the features offered by said plugin. With a converter, I'm allowing people who have been *wanting* to use TeslaCrate the ability to migrate *without* loosing their configuration - a huge step towards this goal, which is why it was desired by so many people. It is your prerogative to implement your own converter if you so desire, however as I'm sure you've found supporting the advanced syntax of TeslaCrate will require a redesign to your own system.

My largest complaint is that this entire issue was specifically designed as an ad-hoc revenge attempt for having the audacity to add a system that would remove users from your own plugin. This event went far enough for you to imply (and to some extent, enact) changes to your configuration system for the sole purposes of breaking my converter. That alone, regardless of anything else, is the most distasteful and disrespectful thing in this entire issue.

The converter will remain a part of TeslaCrate until I see fit that it is no longer required, and will be updated in accordance when necessary. Good day.
